id: UnEscapeURL-Test
version: -1
name: UnEscapeURL-Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: a6c3ede7-6336-4795-8c55-5242486211c0
    type: start
    task:
      id: a6c3ede7-6336-4795-8c55-5242486211c0
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1555,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "1":
    id: "1"
    taskid: ce5e9387-550f-4374-86e9-b04e1d2a7545
    type: regular
    task:
      id: ce5e9387-550f-4374-86e9-b04e1d2a7545
      version: -1
      name: Delete Context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
      - "4"
      - "9"
      - "10"
      - "15"
      - "17"
      - "20"
      - "22"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1555,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "3":
    id: "3"
    taskid: dcbd8e0f-59f4-4b66-8bca-16de10c03a38
    type: regular
    task:
      id: dcbd8e0f-59f4-4b66-8bca-16de10c03a38
      version: -1
      name: UnescapeUrl
      scriptName: UnEscapeURLs
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      input:
        simple: https://urldefense.proofpoint.com/v2/url?u=http-3A__go.getpostman.com_y4wULsdG0h0DDMY0Dv00100&d=DwMFaQ&c=ywDJJevdGcjv4rm9P3FcNg&r=s5kA2oIAQRXsacJiBKmTORIWyRN39ZKhobje2GyRgNs&m=vN1dVSiZvEoM9oExtQqEptm9Dbvq9tnjACDZzrBLaWI&s=zroN7KQdBCPBOfhOmv5SP1DDzZKZ1y9I3x4STS5PbHA&e=
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "4":
    id: "4"
    taskid: d5eeb0fc-46da-4538-860e-2b6e7b9a34c4
    type: regular
    task:
      id: d5eeb0fc-46da-4538-860e-2b6e7b9a34c4
      version: -1
      name: UnEscapeUrl
      scriptName: UnEscapeURLs
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      input:
        simple: https://urldefense.proofpoint.com/v2/url?u=http-3A__maokvo.eu&d=DwMFAg&c=o6x-uYg5urBaLMPPRuq64I5b6ZOFWaPdobkZ8TbBW7M&r=0dtZ_EttZY1gHOgGdV-z-dFmoGOY7zdlOVi7L2EIj14&m=xskGZ0jNEJDRYL6ypuSoCj4YX6FMH8DqJ2l2jNxFL6I&s=KqZlmY1ZrCNVyIId8ADYgiCYNpzbB7-qmlmzv-KqYMs&e=
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "5":
    id: "5"
    taskid: a197d385-a224-4ee0-8be8-b25d34f411c9
    type: regular
    task:
      id: a197d385-a224-4ee0-8be8-b25d34f411c9
      version: -1
      name: Check Url
      scriptName: VerifyHumanReadableContains
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      humanReadableEntryId:
        simple: ${lastCompletedTaskEntries}
      substring:
        simple: http://go.getpostman.com/y4wULsdG0h0DDMY0Dv00100
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "6":
    id: "6"
    taskid: b13da75b-a668-4d4b-8939-0a08ea235773
    type: title
    task:
      id: b13da75b-a668-4d4b-8939-0a08ea235773
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1770,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "8":
    id: "8"
    taskid: 941d0bb5-77ec-4c2e-8091-687c808166fa
    type: regular
    task:
      id: 941d0bb5-77ec-4c2e-8091-687c808166fa
      version: -1
      name: Check Url
      scriptName: VerifyHumanReadableContains
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      humanReadableEntryId:
        simple: ${lastCompletedTaskEntries}
      substring:
        simple: http://maokvo.eu
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "9":
    id: "9"
    taskid: 41c4898a-c7cd-4de9-8169-d66205d9fdf5
    type: regular
    task:
      id: 41c4898a-c7cd-4de9-8169-d66205d9fdf5
      version: -1
      name: UnEscapeURL - ATP Safelink
      scriptName: UnEscapeURLs
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      input:
        simple: na01.safelinks.protection.outlook.com/?url=http%3a%2f%2fwww.avanan.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "10":
    id: "10"
    taskid: a1b2d7fc-c644-43af-8494-be28aa019973
    type: regular
    task:
      id: a1b2d7fc-c644-43af-8494-be28aa019973
      version: -1
      name: UnEscapeURL - ATP Safelink
      scriptName: UnEscapeURLs
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "13"
    scriptarguments:
      input:
        simple: https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftwitter.com%2FPhilipsBeLux&data=02|01||cb2462dc8640484baf7608d638d2a698|1a407a2d76754d178692b3ac285306e4|0|0|636758874714819880&sdata=dnJiphWFhnAKsk5Ps0bj0p%2FvXVo8TpidtGZcW6t8lDQ%3D&reserved=0%3E%5bcid:image003.gif@01CF4D7F.1DF62650%5d%3C
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "12":
    id: "12"
    taskid: c9ca5797-b091-4e24-8d9f-8bca1cbd75a0
    type: regular
    task:
      id: c9ca5797-b091-4e24-8d9f-8bca1cbd75a0
      version: -1
      name: Check URL
      scriptName: VerifyHumanReadableContains
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      humanReadableEntryId:
        simple: ${lastCompletedTaskEntries}
      substring:
        simple: http://www.avanan.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 910,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "13":
    id: "13"
    taskid: 31f2ab5b-145b-463a-8751-04cf9b4355d0
    type: regular
    task:
      id: 31f2ab5b-145b-463a-8751-04cf9b4355d0
      version: -1
      name: Check URL
      scriptName: VerifyHumanReadableContains
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      humanReadableEntryId:
        simple: ${lastCompletedTaskEntries}
      substring:
        simple: https://twitter.com/PhilipsBeLux
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "15":
    id: "15"
    taskid: f1fb8001-e42d-41b9-8144-d2b58508b6d4
    type: regular
    task:
      id: f1fb8001-e42d-41b9-8144-d2b58508b6d4
      version: -1
      name: UnEscapeURL
      scriptName: UnEscapeURLs
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "16"
    scriptarguments:
      input:
        simple: hxxps://www[.]demisto[.]com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1770,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "16":
    id: "16"
    taskid: 77f41c5d-5192-4e50-8115-c51456cd8b5e
    type: regular
    task:
      id: 77f41c5d-5192-4e50-8115-c51456cd8b5e
      version: -1
      name: Check URL
      scriptName: VerifyHumanReadableContains
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      humanReadableEntryId:
        simple: ${lastCompletedTaskEntries}
      substring:
        simple: https://www.demisto.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1770,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "17":
    id: "17"
    taskid: 01e79183-d7c5-4389-816a-05aeb3267264
    type: regular
    task:
      id: 01e79183-d7c5-4389-816a-05aeb3267264
      version: -1
      name: UnEscapeURLs an Array of urls
      description: |-
        Extract original URLs from Protected URLs from security tools like Proofpoint and and Microsoft ATP.
        Changes https://urldefense.proofpoint.com/v2/url?u=https-3A__example.com_something.html -> https://example.com/something.html
        Changes na01.safelinks.protection.outlook.com/?url=https%3a%2f%2fexample.com -> https://example.com
        Also, un-escape URLs that are escaped for safety with formats like hxxps://www[.]demisto[.]com
      scriptName: UnEscapeURLs
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "18"
      - "19"
    scriptarguments:
      input:
        simple: https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.facebook.com%2FPhilipsBeLux&data=02|01||cb2462dc8640484baf7608d638d2a698|1a407a2d76754d178692b3ac285306e4|0|0|636758874714819880&sdata=rSVqfaVO2V23rdg6L7rly%2BbWdn4WmvUk1T5YQ8%2BACbk%3D&reserved=0%3E,https://urldefense.proofpoint.com/v2/url?u=http-3A__go.getpostman.com_y4wULsdG0h0DDMY0Dv00100&d=DwMFaQ&c=ywDJJevdGcjv4rm9P3FcNg&r=s5kA2oIAQRXsacJiBKmTORIWyRN39ZKhobje2GyRgNs&m=vN1dVSiZvEoM9oExtQqEptm9Dbvq9tnjACDZzrBLaWI&s=zroN7KQdBCPBOfhOmv5SP1DDzZKZ1y9I3x4STS5PbHA&e=,hxxps://www[.]demisto[.]com,https://google.com,www.spotify.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 2415,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "18":
    id: "18"
    taskid: 4f33e48e-1142-4fa8-820b-aabd26b9c3b6
    type: regular
    task:
      id: 4f33e48e-1142-4fa8-820b-aabd26b9c3b6
      version: -1
      name: Check URL
      scriptName: VerifyHumanReadableContains
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      humanReadableEntryId:
        complex:
          root: lastCompletedTaskEntries
          transformers:
          - operator: atIndex
            args:
              index:
                value:
                  simple: "2"
      substring:
        simple: https://www.demisto.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 2200,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "19":
    id: "19"
    taskid: bc08f43f-580a-4641-8546-064f03f71838
    type: regular
    task:
      id: bc08f43f-580a-4641-8546-064f03f71838
      version: -1
      name: Check URL
      scriptName: VerifyHumanReadableContains
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      humanReadableEntryId:
        complex:
          root: lastCompletedTaskEntries
          transformers:
          - operator: atIndex
            args:
              index:
                value:
                  simple: "0"
      substring:
        simple: https://www.facebook.com/PhilipsBeLux
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 2630,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "20":
    id: "20"
    taskid: 10573170-0e85-40db-8de7-c46fa3377a71
    type: regular
    task:
      id: 10573170-0e85-40db-8de7-c46fa3377a71
      version: -1
      name: UnEscapeURL with capitalized 'HTTPS'
      description: |-
        Extract original URLs from Protected URLs from security tools like Proofpoint and and Microsoft ATP.
        Changes https://urldefense.proofpoint.com/v2/url?u=https-3A__example.com_something.html -> https://example.com/something.html
        Changes na01.safelinks.protection.outlook.com/?url=https%3a%2f%2fexample.com -> https://example.com
        Also, un-escape URLs that are escaped for safety with formats like hxxps://www[.]demisto[.]com
      scriptName: UnEscapeURLs
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "21"
    scriptarguments:
      extend-context:
        simple: output=
      input:
        simple: HTTPS://autodesk.com/POSTSTUFF
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 3060,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "21":
    id: "21"
    taskid: 9a753c1d-ff82-4ce0-8560-699d3adba881
    type: condition
    task:
      id: 9a753c1d-ff82-4ce0-8560-699d3adba881
      version: -1
      name: Verify that the output URL is correct
      description: Check whether the values provided in arguments are equal. If either
        of the arguments are missing, no is returned.
      scriptName: AreValuesEqual
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "6"
    scriptarguments:
      left:
        complex:
          root: output
      right:
        simple: HTTPS://autodesk.com/POSTSTUFF
    results:
    - AreValuesEqual
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 3060,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "22":
    id: "22"
    taskid: 19bd9528-0d70-45fa-8bc1-ecd10cd8afb7
    type: regular
    task:
      id: 19bd9528-0d70-45fa-8bc1-ecd10cd8afb7
      version: -1
      name: UnEscapeURL - backward slash
      description: |-
        Extract URLs redirected by security tools like Proofpoint.
        Changes https://urldefense.proofpoint.com/v2/url?u=https-3A__example.com_something.html -> https://example.com/something.html
        Also, un-escape URLs that are escaped for safety with formats like hxxps://www[.]demisto[.]com
      scriptName: UnEscapeURLs
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "23"
    scriptarguments:
      input:
        simple: https:\\example.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 3490,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "23":
    id: "23"
    taskid: bc2789f2-244e-4eac-8c70-235da5e655d2
    type: regular
    task:
      id: bc2789f2-244e-4eac-8c70-235da5e655d2
      version: -1
      name: Check Url
      description: Verify given entry contains a string
      scriptName: VerifyHumanReadableContains
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      humanReadableEntryId:
        simple: ${lastCompletedTaskEntries}
      substring:
        simple: http://example.com
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 3490,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 735,
        "width": 3820,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
