id: PhishlabsIOC_EIR-Test
version: -1
name: PhishlabsIOC_EIR-Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 7d35bf19-7c52-4fc2-8071-4e78cae142ad
    type: start
    task:
      id: 7d35bf19-7c52-4fc2-8071-4e78cae142ad
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "1":
    id: "1"
    taskid: 1c45367e-7855-448a-8219-a240382927bd
    type: regular
    task:
      id: 1c45367e-7855-448a-8219-a240382927bd
      version: -1
      name: Delete entry context
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "2":
    id: "2"
    taskid: 6cbdd95d-6a3a-4e69-80e3-1576b15defe0
    type: regular
    task:
      id: 6cbdd95d-6a3a-4e69-80e3-1576b15defe0
      version: -1
      name: Get incident by ID command
      description: Returns a single Incident based on the given ID.
      script: '|||phishlabs-ioc-eir-get-incident-by-id'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      incident_id:
        simple: INC0660932
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "3":
    id: "3"
    taskid: a052d7c7-c8c1-41ee-81f1-bee9038df0ce
    type: condition
    task:
      id: a052d7c7-c8c1-41ee-81f1-bee9038df0ce
      version: -1
      name: 'Check get incident by id '
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "8"
      "yes":
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: PhishLabsIOC.EIR.CaseType
            iscontext: true
      - - operator: isExists
          left:
            value:
              simple: PhishLabsIOC.EIR.Email.EmailBody
            iscontext: true
      - - operator: isExists
          left:
            value:
              simple: PhishLabsIOC.EIR.Email.URL.URL
            iscontext: true
    view: |-
      {
        "position": {
          "x": 265,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "4":
    id: "4"
    taskid: 6556094d-07f8-46d3-80da-50b4b104b16f
    type: regular
    task:
      id: 6556094d-07f8-46d3-80da-50b4b104b16f
      version: -1
      name: PrintContext
      description: Pretty-print the contents of the playbook context
      scriptName: PrintContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      outputformat:
        simple: ${PhishLabsIOC.EIR}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "5":
    id: "5"
    taskid: 66ba19ee-cbfc-4ca1-8f05-f64001a6edb8
    type: regular
    task:
      id: 66ba19ee-cbfc-4ca1-8f05-f64001a6edb8
      version: -1
      name: Get incidents command
      description: Get EIR incidents from PhishLabs-IOC EIR service (dafault limit
        50 incidents)
      script: '|||phishlabs-ioc-eir-get-incidents'
      type: regular
      iscommand: true
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      closed_after: {}
      closed_before: {}
      created_after: {}
      created_before: {}
      direction: {}
      limit: {}
      offset: {}
      sort: {}
      status: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 265,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "7":
    id: "7"
    taskid: 40e66672-da96-4fd7-8bb9-b88735a3cad6
    type: regular
    task:
      id: 40e66672-da96-4fd7-8bb9-b88735a3cad6
      version: -1
      name: PrintContext
      description: Pretty-print the contents of the playbook context
      scriptName: PrintContext
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      outputformat:
        simple: ${PhishLabsIOC.EIR}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "8":
    id: "8"
    taskid: c9e8471d-ca67-4974-82e5-8a3e50872557
    type: regular
    task:
      id: c9e8471d-ca67-4974-82e5-8a3e50872557
      version: -1
      name: PrintErrorEntry
      description: Prints an error entry with a given message
      scriptName: PrintErrorEntry
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      message:
        simple: ${PhishLabsIOC.EIR}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 480,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "9":
    id: "9"
    taskid: 860c5ed0-df56-4ea3-8c31-c419c311ed3f
    type: condition
    task:
      id: 860c5ed0-df56-4ea3-8c31-c419c311ed3f
      version: -1
      name: Check get incidents command
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "10"
      "yes":
      - "7"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              simple: PhishLabsIOC.EIR.CaseType
            iscontext: true
      - - operator: isExists
          left:
            value:
              simple: PhishLabsIOC.EIR.Email.EmailBody
            iscontext: true
      - - operator: isExists
          left:
            value:
              simple: PhishLabsIOC.EIR.Email.URL.URL
            iscontext: true
    view: |-
      {
        "position": {
          "x": 265,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "10":
    id: "10"
    taskid: b9d2ff1a-7fb8-43d7-8bb9-444d643821c8
    type: regular
    task:
      id: b9d2ff1a-7fb8-43d7-8bb9-444d643821c8
      version: -1
      name: PrintErrorEntry
      description: Prints an error entry with a given message
      scriptName: PrintErrorEntry
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      message:
        simple: ${PhishLabsIOC.EIR}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1290,
        "width": 810,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
